# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='high_score',
            field=models.IntegerField(default=0, verbose_name='高考分数'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='learn',
            field=models.IntegerField(choices=[(0, '暂无'), (1, '本科'), (2, '研究生')], default=0, verbose_name='学历'),
        ),
    ]
