# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacherapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirm', models.CharField(blank=True, max_length=255, null=True, verbose_name='证书')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='教师')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
