# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacherconfirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherapply',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='teacherapply',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacherfollowers',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='teacherfollowers',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='TeacherApply',
        ),
        migrations.DeleteModel(
            name='TeacherFollowers',
        ),
    ]
