# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacherfollowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='learn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Learn', verbose_name='学历'),
        ),
    ]
