# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20180313_2232'),
        ('teacher', '0004_auto_20180313_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherfollowers',
            name='follower_id',
        ),
        migrations.AddField(
            model_name='teacherfollowers',
            name='customer',
            field=models.ForeignKey(help_text='收藏用户', null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
