# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20180313_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.City', verbose_name='城市'),
        ),
    ]
