# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fav_id', models.IntegerField(default=0, help_text='被收藏者id')),
                ('fav_type', models.IntegerField(choices=[(1, '教师'), (2, '学生')], default=1, help_text='1: 教师 2: 学生')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('req_id', models.IntegerField(default=0, help_text='被申请者id')),
                ('req_type', models.IntegerField(choices=[(1, '教师'), (2, '学生')], default=1, help_text='1: 教师 2: 学生')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'verbose_name': '用户申请',
                'verbose_name_plural': '用户申请',
            },
        ),
    ]
