# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-19 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WXUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('openid', models.CharField(max_length=200, unique=True, verbose_name='微信id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
