# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_userfavorite_userrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
