# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180310_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavorite',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='userrequest',
            old_name='user',
            new_name='customer',
        ),
    ]
