# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180320_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=640, null=True, verbose_name='投诉原因')),
                ('detailed', models.CharField(blank=True, max_length=640, null=True, verbose_name='具体说明')),
                ('suggestion_obj', models.IntegerField(choices=[(0, '平台'), (1, '教师'), (2, '学生')], default=0, help_text='0: 平台 1: 教师 2: 学生', verbose_name='投诉对象')),
                ('is_valid', models.BooleanField(default=False, verbose_name='是否处理')),
            ],
            options={
                'verbose_name': '投诉反馈',
                'verbose_name_plural': '投诉反馈',
            },
        ),
    ]
