# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180310_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.IntegerField(choices=[(1, '教师'), (2, '学生')], default=1, help_text='1: 教师 2: 学生', verbose_name='用户角色'),
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
        migrations.DeleteModel(
            name='UserRequest',
        ),
    ]
