# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customersuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersuggestion',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='customersuggestion',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否处理'),
        ),
    ]
