# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_suggestionreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersuggestion',
            name='suggestion_obj',
            field=models.IntegerField(default=0, help_text='0: 平台 1: 教师 2: 学生', verbose_name='投诉对象'),
        ),
    ]
