# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20180322_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersuggestion',
            name='reason',
        ),
    ]
