# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=32, verbose_name='\u57ce\u5e02\u7f16\u7801')),
                ('name', models.CharField(max_length=32, verbose_name='\u57ce\u5e02\u540d\u79f0')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
