# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64, verbose_name='原因')),
            ],
            options={
                'verbose_name': '原因',
                'verbose_name_plural': '原因',
            },
        ),
    ]
