# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_baselevel_level_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64, verbose_name='\u5b66\u6821\u540d\u79f0')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.City', verbose_name=b'\xe5\x9f\x8e\xe5\xb8\x82')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
