# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_reason_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(max_length=640, verbose_name='问题')),
                ('text', models.TextField(blank=True, null=True, verbose_name='帮助')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': '使用帮助',
                'verbose_name_plural': '使用帮助',
            },
        ),
    ]
