# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.City', verbose_name='城市'),
        ),
    ]
