# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20180301_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200, verbose_name='存在问题')),
            ],
            options={
                'verbose_name': '学生存在问题',
                'verbose_name_plural': '学生存在问题',
            },
        ),
        migrations.CreateModel(
            name='TeacherType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200, verbose_name='特点')),
            ],
            options={
                'verbose_name': '教师特点',
                'verbose_name_plural': '教师特点',
            },
        ),
        migrations.AlterModelOptions(
            name='baselevel',
            options={'verbose_name': '学校等级', 'verbose_name_plural': '学校等级'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': '年级', 'verbose_name_plural': '年级'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校', 'verbose_name_plural': '学校'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '科目', 'verbose_name_plural': '科目'},
        ),
    ]
