# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_reason_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='checked',
        ),
    ]
