# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_basis_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='level',
            field=models.CharField(default=985, max_length=24, verbose_name='学校等级'),
        ),
    ]
