# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_school_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttype',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='是否选中'),
        ),
        migrations.AddField(
            model_name='subject',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='是否选中'),
        ),
        migrations.AddField(
            model_name='teachertype',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='是否选中'),
        ),
    ]
