# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0010_remove_customersuggestion_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_id', models.IntegerField(default=0, verbose_name='申请对象id')),
                ('target_type', models.CharField(max_length=64, verbose_name='申请对象')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('customer_type', models.CharField(max_length=64, verbose_name='用户收藏时身份')),
                ('customer_type_id', models.IntegerField(verbose_name='用户身份id')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户申请',
                'verbose_name_plural': '用户申请',
            },
        ),
        migrations.CreateModel(
            name='CustomerFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_id', models.IntegerField(default=0, verbose_name='收藏对象id')),
                ('target_type', models.CharField(max_length=64, verbose_name='收藏对象')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('customer_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户收藏时身份')),
                ('customer_type_id', models.IntegerField(default=0, verbose_name='用户身份id')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
    ]
