# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_customersuggestion_reason'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerapply',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerapply',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='customerapply',
            name='customer_type_id',
        ),
        migrations.RemoveField(
            model_name='customerfavorite',
            name='customer_type_id',
        ),
        migrations.AddField(
            model_name='customerapply',
            name='apply_obj_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='申请对象当时身份'),
        ),
        migrations.AddField(
            model_name='customerapply',
            name='apply_obj_type_id',
            field=models.IntegerField(default=0, verbose_name='申请对象当时身份id'),
        ),
        migrations.AddField(
            model_name='customerapply',
            name='customer_apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='申请对象用户'),
        ),
        migrations.AlterField(
            model_name='customerapply',
            name='target_id',
            field=models.IntegerField(default=0, verbose_name='申请者id'),
        ),
        migrations.AlterField(
            model_name='customerapply',
            name='target_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='申请者类型'),
        ),
    ]
