# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180327_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerapply',
            name='target_customer_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='申请者用户id'),
        ),
        migrations.AlterField(
            model_name='customerapply',
            name='apply_obj_type_id',
            field=models.IntegerField(default=0, verbose_name='申请对象当时身份id, 教师 or 学生'),
        ),
    ]
