# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180327_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerapply',
            old_name='target_customer_id',
            new_name='apply_customer_id',
        ),
        migrations.RenameField(
            model_name='customerapply',
            old_name='customer_apply',
            new_name='target_customer',
        ),
        migrations.RemoveField(
            model_name='customerapply',
            name='apply_obj_type',
        ),
        migrations.RemoveField(
            model_name='customerapply',
            name='apply_obj_type_id',
        ),
        migrations.AddField(
            model_name='customerapply',
            name='apply_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='申请者当时身份'),
        ),
        migrations.AddField(
            model_name='customerapply',
            name='apply_type_id',
            field=models.IntegerField(default=0, verbose_name='申请者当时身份id, 教师 or 学生'),
        ),
        migrations.AlterField(
            model_name='customerapply',
            name='target_id',
            field=models.IntegerField(default=0, verbose_name='申请对象id'),
        ),
        migrations.AlterField(
            model_name='customerapply',
            name='target_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='申请对象类型'),
        ),
    ]
