# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_baselevel_level_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(max_length=16, verbose_name='\u7535\u8bdd')),
                ('study', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5b66\u4e60\u60c5\u51b5')),
                ('times', models.IntegerField(default=1, help_text='1\uff1a\u4e00\u5468\u4e00\u6b21\uff0c 2\uff1a\u4e00\u54682\u6b21\uff0c\u4f9d\u6b21\u5185\u63a8\uff0c\u6700\u59277\u6b21, 0: \u9762\u8bae', verbose_name='\u8865\u4e60\u6b21\u6570')),
                ('money', models.CharField(default='\u9762\u8bae', max_length=12, verbose_name='\u91d1\u94b1')),
                ('require', models.CharField(default='\u4e0d\u9650', max_length=32, verbose_name='\u6559\u5e08\u8d44\u8d28')),
                ('sex', models.IntegerField(default=0, help_text='0\uff1a\u5973 1\uff1a\u7537', verbose_name='\u6027\u522b\u8981\u6c42')),
                ('address', models.CharField(max_length=128, verbose_name='\u4e0a\u8bfe\u5730\u70b9')),
                ('id_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
                ('extra', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5176\u4ed6')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.City', verbose_name='\u57ce\u5e02')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Level', verbose_name='\u5e74\u7ea7')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Subject', verbose_name='\u5b66\u79d1')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
