# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-18 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsubjectsship',
            old_name='teacher',
            new_name='student',
        ),
    ]
