# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher_sex',
            field=models.IntegerField(default=0, help_text='0\uff1a\u5973 1\uff1a\u7537', verbose_name='\u6559\u5e08\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(default=0, help_text='0\uff1a\u5973 1\uff1a\u7537', verbose_name='\u6027\u522b'),
        ),
    ]
