# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-18 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('student', '0002_auto_20180318_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='baselevel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.BaseLevel', verbose_name='年级'),
        ),
    ]
