# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('student', '0003_auto_20180226_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='\u7528\u6237'),
        ),
    ]
