# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-08 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id_valid',
            new_name='is_valid',
        ),
    ]
