# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentrapply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfollowers',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='studentfollowers',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentrapply',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='studentrapply',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentFollowers',
        ),
        migrations.DeleteModel(
            name='StudentrApply',
        ),
    ]
