# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180325_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='head_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='头像'),
        ),
    ]
