# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_basis_learn'),
        ('student', '0007_studentfollowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='basis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Basis', verbose_name='学生基础'),
        ),
    ]
