# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20180313_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.City', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='student',
            name='times',
            field=models.CharField(default='一周一次', help_text='1：一周一次， 2：一周2次，依次内推，最大7次, 0: 面议', max_length=64, verbose_name='补习次数'),
        ),
    ]
