# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20180315_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='study',
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.City', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='student',
            name='require',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.TeacherRequire', verbose_name='教师资质'),
        ),
    ]
