# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-18 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20180318_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='require',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.TeacherRequire', verbose_name='教师资质'),
        ),
    ]
